name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # runs every day at midnight
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: kwamevaughan
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Push to output branch using PAT
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          git clone https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/kwamevaughan/kwamevaughan.git --branch output --single-branch output-dir
          cp -r dist/* output-dir/

          cd output-dir
          git add .
          git commit -m "Update contribution snake" || echo "No changes to commit"
          git push origin output
